name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
    deploy_to_server:
      description: 'Actually deploy to the server?'
      required: true
      type: boolean
      default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bash tools
        run: sudo apt-get update && sudo apt-get install -y zip unzip shellcheck

      - name: Lint with shellcheck
        run: shellcheck main.sh test.sh

      - name: Run tests
        run: |
          chmod +x test.sh
          ./test.sh

      - name: Package artifact
        run: zip release.zip main.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bash-sample
          path: release.zip
