name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_to_server:
        description: "Actually deploy?"
        required: true
        type: boolean
        default: false

permissions:
  contents: read     # default for checkout, shellcheck etc.
  actions: read      # for download-artifact

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build & test
        run: |
          sudo apt-get update && sudo apt-get install -y zip unzip shellcheck
          shellcheck main.sh test.sh
          chmod +x test.sh && ./test.sh

      - name: package
        run: zip release.zip main.sh

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bash-sample
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_to_server == 'true' }}
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: bash-sample
          path: deploy

      - name: unzip
        run: |
          cd deploy
          unzip release.zip

      - name: scp to server
        env:
          USER: ${{ secrets.DEPLOY_USER }}
          SERVER: ${{ secrets.DEPLOY_SERVER }}
          PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER >> ~/.ssh/known_hosts
          scp deploy/main.sh $USER@$SERVER:/home/$USER/DEPLOY/
