name: Update Release Notes

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Update release notes
        run: |
          bash scripts/update_release_notes.sh ${{ github.event.before }} ${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add RELEASE_NOTES.md
          if git diff --cached --quiet; then
            echo "No release notes to update"
          else
            git commit -m "chore: update release notes"
            git push
          fi